routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use PHPUnit\Event\Code\Test;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\HomeController;
use Spatie\Activitylog\Models\Activity;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function () {
    // return Activity::all();
    return view('welcome');
});

Auth::routes();
Route::get('/historical', [App\Http\Controllers\HistoricalController::class, 'index']);
Route::get('/Dashboard', [App\Http\Controllers\DashboardController::class, 'countAdmin']);
Route::get('/Profile', [App\Http\Controllers\AdminController::class, 'profile']);
Route::get('/home', [App\Http\Controllers\AdminController::class, 'index']);
Route::get('/admin', [App\Http\Controllers\HomeController::class, 'index'])->name('tasks.index');
Route::get('/register', [App\Http\Controllers\RegistrationController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [App\Http\Controllers\RegistrationController::class, 'registerUser'])->name('register.user');
Route::get('/test', [App\Http\Controllers\RegistrationController::class, 'index']);
Route::delete('/test/{id}', [App\Http\Controllers\RegistrationController::class, 'destroy'])->name('register.destroy');
Route::get('/Reports', [App\Http\Controllers\ReportController::class, 'index']);

Route::get('getTask',[HomeController::class,'getTask']);
Route::get('UpdateProjet',[ProjectController::class,'UpdateProjet']);
Route::get('getproject',[ProjectController::class,'getproject']);
Route::get('updateUser',[App\Http\Controllers\RegistrationController::class,'updateUser']);
Route::get('getuser',[App\Http\Controllers\RegistrationController::class,'getuser']);
Route::get('updateTask',[HomeController::class,'updateTask']);
Route::post('store',[ProjectController::class,'store']);

Route::delete('/project/{id}', [App\Http\Controllers\HomeController::class, 'destroy'])->name('project.destroy');
Route::middleware('admin')->group(function () {
    Route::post('/admin', [App\Http\Controllers\HomeController::class, 'store'])->name('tasks.store');
    Route::delete('/tasks/{id}', [App\Http\Controllers\HomeController::class, 'destroy'])->name('tasks.destroy');
    Route::get('employees/{id}', [App\Http\Controllers\HomeController::class, 'getEmployees'])->name('employees.getEmployees');
    Route::get('getHistory',[App\Http\Controllers\HomeController::class,'getHistory']);
    Route::resource('projects', ProjectController::class);
    
   
  
});

resources/views/Dashboard.blade.php
@extends('layouts.admin-dash-layout')

@section('content')
   
                <div class="">
                   <!-- WELCOME-->
            <section class="welcome p-t-10">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="title-4">Welcome back
                                <span>{{Auth::user()->name}}</span>
                            </h1>
                            <hr class="line-seprate">
                        </div>
                    </div>
                </div>
            </section>
            <!-- END WELCOME-->

            <!-- STATISTIC-->
            <section class="statistic statistic2">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-lg-3">
                            <div class="statistic__item statistic__item--blue">
                                <h2 class="number">{{$adminCount}}</h2>
                                <span class="desc">Admins</span>
                                <div class="icon">
                                    <i class="zmdi zmdi-account-o"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="statistic__item statistic__item--blue">
                                <h2 class="number">{{$memberCount}}</h2> 
                                <span class="desc">Members</span>
                                <div class="icon">
                                    <i class="zmdi zmdi-account-o"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="statistic__item statistic__item--blue">
                                <h2 class="number">{{$report}}</h2>
                                <span class="desc">Completed tasks</span>
                                <div class="icon">
                                    <i class="zmdi zmdi-calendar-note"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div class="statistic__item statistic__item--blue">
                                <h2 class="number">{{$project}}</h2>
                                <span class="desc">Projects</span>
                                <div class="icon">
                                    <i class="zmdi zmdi-money"></i>
                                </div>
                            </div>
                           
                           
                        </div>
                    </div>
                </div>
            </section>
            <!-- END STATISTIC-->
            <section class="statistic statistic2">
                <div class="container">
                   <div class="row">
                       <div class="col-md-6 col-lg-3">
                           <div class="statistic__item statistic__item--red">
                               <h2 class="number">{{$tasks}}</h2>
                               <span class="desc">Pending Tasks</span>
                               <div class="icon">
                                   <i class="zmdi "></i>
                               </div>
                           </div>
                       </div>
                       {{-- <div class="col-md-6 col-lg-3">
                        <div class="statistic__item statistic__item--blue">
                            <h2 class="number">{{$report}}</h2>
                            <span class="desc">Completed tasks</span>
                            <div class="icon">
                                <i class="zmdi zmdi-calendar-note"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="statistic__item statistic__item--blue">
                            <h2 class="number">{{$report}}</h2>
                            <span class="desc">Completed tasks</span>
                            <div class="icon">
                                <i class="zmdi zmdi-calendar-note"></i>
                            </div>
                        </div> --}}
                    </div>
                       </div>
                      
                               
           </section>
                </div>
            
            </div>
       

@endsection

resources/views/Profile.blade.php
@extends('layouts.admin-dash-layout')

@section('content')
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Profile</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">User Profile</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3">

          <!-- Profile Image -->
          <div class="card card-primary card-outline">
            <div class="card-body box-profile">
              <div class="text-center">
                <img class="profile-user-img img-fluid img-circle"
                  src="{{Auth::user()->picture}}"
                     alt="User profile picture">
              </div>

              <h3 class="profile-username text-center">{{Auth::user()->name}}</h3>

              <p class="text-muted text-center">{{Auth::user()->status}}</p>
<!-- About Me Box -->
<div class="card card-primary">
  <div class="card-header">
    <h3 class="card-title">About Me</h3>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <strong><i class="fas fa-book mr-1"></i> Education</strong>

    <p class="text-muted">
      B.S. in Computer Science from the University of Tennessee at Knoxville
    </p>

    <hr>

    <strong><i class="fas fa-map-marker-alt mr-1"></i> Phone number</strong>

    <p class="text-muted">{{Auth::user()->phone_number}}</p>

    <hr>

    <strong><i class="fas fa-pencil-alt mr-1"></i>skills</strong>

    <p class="text-muted">
      <span class="tag tag-danger">{{Auth::user()->skills}}</span>
    
    </p>

    <hr>

    <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>

    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
  </div>
              
            
            </div>
            <!-- /.card-body -->
          </div>
          


@endsection

resources/views/Reports.blade.php
@extends('layouts.admin-dash-layout')

@section('content')
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script> 
    <div class="card-body p-0">
        <div class="row justify-content-center">
            <div class="col-md-8">   
                <div class="card">
                    <div class="card-header">Report</div>
                    @if (Auth::user()->is_admin !==1)
                      <div class="card-body">
                              <p>You are not authorized to access this page.</p>
                            </div> 
                        </div>   
                   </div> 
               </div> 
                @else
                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                   
                    <table class="table" id="tableProjet">
                        <thead>
                            <tr>
                                <th>Priority</th>
                                <th>todo</th>
                                <th>type</th>
                                <th>deadline</th>
                                <th>status</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($Reports as $report)
                                <tr>
                                    <td>{{ $report->projectname }}</td>
                                    <td>{{ $report->todo }}</td>
                                    <td>{{ $report->type }}</td>
                                    <td>{{ $report->deadline }}</td>
                                    <td>{{ $report->status }}</td>
                                </tr>
                            @endforeach
                            @endif
 
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    @endsection
  

resources/views/historical.blade.php
@extends('layouts.admin-dash-layout')

@section('content')



<div class="card">
    <div class="card-header actions-toolbar">
      <div class="actions-search" id="actions-search">
        <div class="input-group input-group-merge input-group-flush">
          <div class="input-group-prepend">
            <span class="input-group-text bg-transparent"><i class="fas fa-search"></i></span>
          </div>
          <input type="text" class="form-control form-control-flush" placeholder="Type and hit enter ...">
          <div class="input-group-append">
            <a href="#" class="input-group-text bg-transparent" data-action="search-close" data-target="#actions-search"><i class="fas fa-times"></i></a>
          </div>
        </div>
      </div>
      <div class="row justify-content-between align-items-center">
        <div class="col-lg col-md col-12">
          <h6 class="text-uppercase d-inline-block mb-0">Historical</h6>
        </div>
       
        <div class="col d-flex align-items-center justify-content-between justify-content-md-end">
          <div class="actions d-inline-block">
            <a href="#" class="action-item mr-3" data-action="search-open" data-target="#actions-search"><i class="fas fa-search"></i></a>
            <a href="javascript:;" id="grid-view" class="action-item mr-3"><i class="fas fa-th-large"></i></a>
          </div>
         
        </div>
        
      </div>
    </div>
    <div class="card-body">
    @if (Auth::user()->is_admin !==1)
       <div class="card-body">
         <p>You are not authorized to access this page.</p>
        </div>
    @else    
<div class="table-responsive list-content">
        <table class="table table-striped projects"> 
             
            
          <thead>
            <tr>
              <th scope="col">Description</th>
              <th scope="col" class="sort">Event</th>
              <th scope="col" class="sort">User</th>
              <th scope="col" class="sort">Created_at</th>
              <th scope="col">Properties</th>
              
            </tr>
          </thead>
        <tbody>
            @foreach ($logs as $log)
                    <tr>
                        <th>{{ $log->description  }}</th>
                        <td>{{ $log->event  }}</td>
                    @foreach ($users as $user)
                     @if($log->causer_id === $user->id)
                        <td value="{{ $user->id }}" >{{ $user->name }}</td>
                     @endif
                    @endforeach
                       <td>{{$log->created_at}}</td>
                        
                       
                       <td><div>
                        <i class="fa fa-ellipsis-h" onclick="toggleButtons({{ $log->id }})"></i>
                        <div id="buttonsContainer{{ $log->id}}" style="display: none;">{{$log->properties}}</div></td>
            @endforeach
        </tbody>
    </table>

   @endif 
</div>
<script>
    function toggleButtons(logId) {
      var buttonsContainer = document.getElementById("buttonsContainer" + logId);
      if (buttonsContainer.style.display === "none") {
        buttonsContainer.style.display = "block";
      } else {
        buttonsContainer.style.display = "none";
      }
    }
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.admin-dash-layout')

@section('content')
   
                <div class="">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                            
                        </div>
                    @endif

                </div>
            <div>
                    <p>welcome </p>
                </div>
            </div>
       

@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    
</head>
<body>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script> 
    @yield('content')
</body>
</html>

resources/views/projet.blade.php
@extends('layouts.admin-dash-layout')

@section('content')
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script> 
<div>
        
    <button class="w3-button w3-right"  id="addProjectButton">Add new </button>
  </div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            
            <div class="card">

                <div class="card-header">Projects</div>

                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                   
                    <table class="table" id="tableProjet">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Descrption</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($projectts as $project)
                                <tr>
                                    <td>{{ $project->name_project }}</td>
                                    <td>{{ $project->Descrption  }}</td>
                                    <td>
                                        <form action="{{ route('projects.destroy', $project->id) }}" method="POST" style="display: inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                onclick="return confirm('Are you sure you want to delete this project?')">Delete</button>
                                        </form>
                                        <a  class="btn btn-primary btn-sm" id="btnupdate"  value="{{$project->id}}">Edit</a>
                                           
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

  
<div class="modal" tabindex="-1" role="dialog" id="modalUpdat">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">update project</h5>
          
           
        </div>
        <div class="modal-body">
                          <div class="form-group">
                              <label for="name">Name</label>
                              <input type="text" name="name_project" id="name_project" class="form-control" required>
                          </div>
                           <div class="form-group">
                              <label for="Descrption">Descrption</label>
                              <textarea name="Descrption" id="Descrption" class="form-control" required></textarea>
                          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-success" id="btnUdapteProjet" >Update</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  

<script>
 var idprojet = 0;
$('#tableProjet tbody').on('click', '#btnupdate', function() {
    idprojet = $(this).attr('value');
   
    $.ajax({
        type: "get",
        url: "{{url('getproject')}}",
        data: {
            idprojet: $(this).attr('value'),
            
        },
        
        
        dataType: "json",
        success: function(response) {
            if (response.statut == 200 ) {
           
               console.log(response.data[0].name_project);
                $('#name_project').val(response.data[0].name_project);
                 $('#Descrption').val(response.data[0].Descrption); 
                 $('#modalUpdat').modal('show');
            }
        }
        
    });

});

$('#btnUdapteProjet').on('click', function() { 
    $.ajax({
        type: "get",
        url: "{{url('UpdateProjet')}}",
        data: {
          name_project: $('#name_project').val(),
            desc: $('#Descrption').val(), 
            id: idprojet,
        },
        dataType: "json",
        success: function(response) {
            if (response.statut == 200) {
                location.reload();
            }
        }
    });
});

  
    const addProjectButton = document.getElementById('addProjectButton');
const tableBody = document.querySelector('tbody');

addProjectButton.addEventListener('click', function() {
  const newRow = document.createElement('tr');
  newRow.innerHTML = `
    <td><input type="text" name="name_project"></td>
    <td><input type="text" name="Descrption"></td>
    <td>
      <button class="saveButton">save</button>
    </td>
  `;
  tableBody.appendChild(newRow);

  const saveButton = newRow.querySelector('.saveButton');
  saveButton.addEventListener('click', function() {
    const name_project = newRow.querySelector('[name=name_project]').value;
    const Descrption = newRow.querySelector('[name=Descrption]').value;

    $.ajax({
      url: "{{url('store')}}",
      type: "POST",
      data: {
        "_token": "{{ csrf_token() }}",
        "name_project": name_project,
        "Descrption": Descrption
      },
      success: function(response) {
        // Display success message
        if (response.statut == 400) {

          alert('Something went wrong...');
        } else {
           
          location.reload();
        }
      },
      error: function(xhr, status, error) {
        // Display error message
        console.error(xhr.responseText);
        alert('An error occurred while processing the request.');
      }
    });
  });
});


    

</script>
@endsection